import mongoose from 'mongoose'; import request from 'supertest'; import { MongoMemoryReplSet } from 'mongodb-memory-server'; import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest'; import { createApp } from '../app.js'; import type { SessionContext, SessionService } from '../auth/sessionService.js'; import { connectToDatabase, disconnectFromDatabase } from '../database/mongoose.js'; import { AuditEventModel } from '../models/AuditEvent.js'; import { SessionModel } from '../models/Session.js'; import { UnitModel } from '../models/Unit.js'; import { UserModel } from '../models/User.js'; import { hashPassword } from '../models/passwordHash.js'; import { verifyPassword } from '../auth/password.js';
const service = (context: SessionContext): SessionService => ({ async login() { throw new Error('unused'); }, async getSessionContext() { return context; }, async logout() {}, async recordMissingSessionCookie() {} }); const admin = { userId: 'a', name: 'Admin', registration: 'a', role: 'ditel_admin' as const, unit: null }; const local = { userId: 'u', name: 'Local', registration: 'u', role: 'unit_user' as const, unit: { id: 'unit-1', name: 'Centro', acronym: 'CTR' } }; const get = (context: SessionContext, query = '') => request(createApp({ sessionService: service(context) })).get(`/api/v1/admin/users${query}`).set('Cookie', 'sigat_session=test');
const updateSituation = (context: SessionContext, userId: string, body: object) => request(createApp({ sessionService: service(context) })).patch(`/api/v1/admin/users/${userId}/situation`).set('Cookie', 'sigat_session=test').send(body);
const createUser = (context: SessionContext, body: object) => request(createApp({ sessionService: service(context) })).post('/api/v1/admin/users').set('Cookie', 'sigat_session=test').send(body);
const updateUser = (context: SessionContext, userId: string, body: object) => request(createApp({ sessionService: service(context) })).patch(`/api/v1/admin/users/${userId}`).set('Cookie', 'sigat_session=test').send(body);
const updateBody = (user: { updatedAt: Date }, body: object) => ({ ...body, updatedAt: user.updatedAt.toISOString() });
const resetPassword = (context: SessionContext, userId: string, body: object = {}) => request(createApp({ sessionService: service(context) })).post(`/api/v1/admin/users/${userId}/password-reset`).set('Cookie', 'sigat_session=test').send(body);
const deactivateUser = (context: SessionContext, userId: string) => request(createApp({ sessionService: service(context) })).delete(`/api/v1/admin/users/${userId}`).set('Cookie', 'sigat_session=test');
describe('admin user routes', () => { let server: MongoMemoryReplSet; beforeAll(async () => { server = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await connectToDatabase(server.getUri()); }); afterEach(async () => { vi.restoreAllMocks(); await Promise.all(Object.values(mongoose.connection.collections).map((c) => c.deleteMany({}))); }); afterAll(async () => { await disconnectFromDatabase(); await server.stop(); });
  it('requires a session', async () => { expect((await request(createApp()).get('/api/v1/admin/users')).status).toBe(401); });
  it('allows only DITEL admins', async () => { expect((await get(local)).status).toBe(403); });
  it('audits a successful administrative user listing without sensitive fields', async () => { const response = await get(admin); expect(response.status).toBe(200); const event = await AuditEventModel.findOne({ action: 'admin.users.list' }).lean(); expect(event).toMatchObject({ action: 'admin.users.list', userId: 'a', result: 'success', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('audits a forbidden administrative user listing without sensitive fields', async () => { const response = await get(local); expect(response.status).toBe(403); const event = await AuditEventModel.findOne({ action: 'admin.users.list' }).lean(); expect(event).toMatchObject({ action: 'admin.users.list', userId: 'u', result: 'failure', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('blocks an active user and returns the canonical situation', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Alvo', registration: '20', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const response = await updateSituation(admin, user.id, { situation: 'blocked' }); expect(response.status).toBe(200); expect(response.body).toEqual({ id: user.id, situation: 'blocked' }); expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('blocked'); });
  it('unblocks a blocked user and audits the successful transition without sensitive fields', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Alvo', registration: '21', role: 'unit_user', situation: 'blocked', unit: local.unit, passwordHash }); const response = await updateSituation(admin, user.id, { situation: 'active' }); expect(response.status).toBe(200); expect(response.body).toEqual({ id: user.id, situation: 'active' }); const event = await AuditEventModel.findOne({ action: 'admin.users.situation.update' }).lean(); expect(event).toMatchObject({ action: 'admin.users.situation.update', userId: 'a', result: 'success', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('audits a situation update with actor, entity, unit and before/after snapshots', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Alvo Auditado', registration: '24', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const response = await updateSituation(admin, user.id, { situation: 'blocked' }); const event = await AuditEventModel.findOne({ action: 'admin.users.situation.update', result: 'success' }).lean(); expect(response.status).toBe(200); expect(event).toMatchObject({ action: 'admin.users.situation.update', module: 'administration', userId: 'a', actor: { id: 'a', name: 'Admin', registration: 'a', role: 'ditel_admin' }, entity: { type: 'user', id: user.id, label: 'Alvo Auditado' }, unit: local.unit, result: 'success', reason: null, before: { situation: 'active' }, after: { situation: 'blocked' } }); expect(event?.retentionExpiresAt).toEqual(expect.any(Date)); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i); });
  it('rolls back a situation update and returns a controlled error when the success audit fails', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Rollback Audit', registration: '25', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); vi.spyOn(AuditEventModel, 'create').mockRejectedValueOnce(new Error('simulated audit outage') as never); const response = await updateSituation(admin, user.id, { situation: 'blocked' }); expect(response.status).toBe(503); expect(response.body).toEqual({ code: 'AUDIT_UNAVAILABLE', message: 'Não foi possível registrar auditoria.' }); expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('active'); });
  it('allows only one concurrent situation transition and audits both outcomes', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Concorrente', registration: 'concurrent', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const responses = await Promise.all([updateSituation(admin, user.id, { situation: 'blocked' }), updateSituation(admin, user.id, { situation: 'blocked' })]); expect(responses.map((response) => response.status).sort((a, b) => a - b)).toEqual([200, 409]); expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('blocked'); const events = await AuditEventModel.find({ action: 'admin.users.situation.update' }).lean(); expect(events).toHaveLength(2); expect(events.map((event) => event.result).sort()).toEqual(['failure', 'success']); expect(JSON.stringify(events)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('rejects an inactive target and leaves its situation unchanged', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Inativo', registration: '22', role: 'unit_user', situation: 'inactive', unit: local.unit, passwordHash }); const response = await updateSituation(admin, user.id, { situation: 'active' }); expect(response.status).toBe(409); expect(response.body.code).toBe('INVALID_SITUATION_TRANSITION'); expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('inactive'); });
  it('rejects malformed or missing update targets', async () => { expect((await updateSituation(admin, 'not-an-object-id', { situation: 'blocked' })).status).toBe(400); expect((await updateSituation(admin, new mongoose.Types.ObjectId().toString(), { situation: 'blocked' })).status).toBe(404); expect((await updateSituation(admin, new mongoose.Types.ObjectId().toString(), { situation: 'inactive' })).status).toBe(400); });
  it('audits an invalid situation payload as a failure', async () => { const response = await updateSituation(admin, new mongoose.Types.ObjectId().toString(), { situation: 'inactive' }); expect(response.status).toBe(400); const event = await AuditEventModel.findOne({ action: 'admin.users.situation.update' }).sort({ createdAt: -1 }).lean(); expect(event).toMatchObject({ action: 'admin.users.situation.update', userId: 'a', result: 'failure', reason: null }); });
  it('allows only DITEL admins to change user situation and audits the failure', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Alvo', registration: '23', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const response = await updateSituation(local, user.id, { situation: 'blocked' }); expect(response.status).toBe(403); expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('active'); const event = await AuditEventModel.findOne({ action: 'admin.users.situation.update' }).lean(); expect(event).toMatchObject({ action: 'admin.users.situation.update', userId: 'u', result: 'failure', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('returns distinct public administrative situations', async () => { const passwordHash = await hashPassword('password'); await UserModel.create([{ name: 'Ativo', registration: '1', role: 'unit_user', active: true, situation: 'active', unit: local.unit, passwordHash }, { name: 'Bloqueado', registration: '2', role: 'unit_user', active: false, situation: 'blocked', unit: local.unit, passwordHash }, { name: 'Inativo', registration: '3', role: 'unit_user', active: false, situation: 'inactive', unit: local.unit, passwordHash }]); const response = await get(admin, '?page=1&pageSize=20'); expect(response.status).toBe(200); expect(response.body.items.map((item: { situation: string }) => item.situation)).toEqual(['active', 'blocked', 'inactive']); expect(response.body.items[0]).not.toHaveProperty('passwordHash'); });
  it('returns exactly the public administrative user contract', async () => { const passwordHash = await hashPassword('password'); await UserModel.create({ name: 'Ana', registration: '10', role: 'unit_user', active: true, unit: local.unit, passwordHash }); const response = await get(admin, '?page=1&pageSize=20'); const item = response.body.items[0]; expect(Object.keys(item).sort()).toEqual(['createdAt', 'id', 'name', 'registration', 'role', 'situation', 'unit', 'updatedAt']); expect(JSON.stringify(response.body)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('applies the combined public filters and preserves pagination', async () => { const passwordHash = await hashPassword('password'); await UserModel.create([{ name: 'Ana', registration: '10', role: 'unit_user', active: true, unit: local.unit, passwordHash }, { name: 'Bruno', registration: '11', role: 'unit_user', active: false, situation: 'blocked', unit: local.unit, passwordHash }]); const response = await get(admin, '?search=Ana&role=unit_user&unitId=unit-1&situation=Ativo&page=1&pageSize=1'); expect(response.body).toMatchObject({ total: 1, page: 1, pageSize: 1 }); expect(response.body.items).toHaveLength(1); expect(response.body.items[0].name).toBe('Ana'); });
  it('rejects invalid query', async () => { expect((await get(admin, '?page=0')).status).toBe(400); expect((await get(admin, '?role=bad')).status).toBe(400); });
  it('creates a unit user with an active unit, hashes the initial password, and returns only the public contract', async () => { await UnitModel.create({ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }); const response = await createUser(admin, { name: '  Nova Usuária  ', registration: ' 30001 ', role: 'unit_user', password: 'senha-inicial-segura', unit: local.unit }); expect(response.status).toBe(201); expect(Object.keys(response.body).sort()).toEqual(['createdAt', 'id', 'name', 'registration', 'role', 'situation', 'unit', 'updatedAt']); expect(response.body).toMatchObject({ name: 'Nova Usuária', registration: '30001', role: 'unit_user', situation: 'active', unit: local.unit }); expect(JSON.stringify(response.body)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); const stored = await UserModel.findOne({ registration: '30001' }).select('+passwordHash').lean().orFail(); const storedPasswordHash = stored.passwordHash as string; expect(storedPasswordHash).not.toBe('senha-inicial-segura'); await expect(verifyPassword('senha-inicial-segura', storedPasswordHash)).resolves.toBe(true); const event = await AuditEventModel.findOne({ action: 'admin.users.create' }).lean(); expect(event).toMatchObject({ action: 'admin.users.create', userId: 'a', result: 'success', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId|senha-inicial-segura/i); });
  it('rolls back user creation when the success audit event cannot be persisted', async () => { await UnitModel.create({ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }); vi.spyOn(AuditEventModel, 'create').mockRejectedValueOnce(new Error('simulated audit outage') as never); const response = await createUser(admin, { name: 'Audit Create Rollback', registration: '30008', role: 'unit_user', password: 'senha-inicial-segura', unit: local.unit }); expect(response.status).toBe(503); expect(response.body).toEqual({ code: 'AUDIT_UNAVAILABLE', message: 'Não foi possível registrar auditoria.' }); expect(await UserModel.countDocuments({ registration: '30008' })).toBe(0); });
  it('updates editable user fields atomically and audits sanitized before/after snapshots', async () => { await UnitModel.create({ id: 'unit-norte', name: 'Unidade Norte', acronym: 'UN', active: true }); const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Alvo Antigo', registration: '50001', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const response = await updateUser(admin, user.id, updateBody(user, { name: ' Alvo Atualizado ', registration: ' 50002 ', role: 'unit_user', unit: { id: 'unit-norte', name: 'Unidade Norte', acronym: 'UN' } })); expect(response.status).toBe(200); expect(Object.keys(response.body).sort()).toEqual(['createdAt', 'id', 'name', 'registration', 'role', 'situation', 'unit', 'updatedAt']); expect(response.body).toMatchObject({ id: user.id, name: 'Alvo Atualizado', registration: '50002', role: 'unit_user', situation: 'active', unit: { id: 'unit-norte', name: 'Unidade Norte', acronym: 'UN' } }); const stored = await UserModel.findById(user.id).select('+passwordHash').lean().orFail(); expect(stored).toMatchObject({ name: 'Alvo Atualizado', registration: '50002', role: 'unit_user', situation: 'active', unit: { id: 'unit-norte', name: 'Unidade Norte', acronym: 'UN' } }); expect(stored.passwordHash).toBe(passwordHash); const event = await AuditEventModel.findOne({ action: 'admin.users.update' }).lean(); expect(event).toMatchObject({ action: 'admin.users.update', module: 'administration', userId: 'a', actor: { id: 'a', name: 'Admin', registration: 'a', role: 'ditel_admin' }, entity: { type: 'user', id: user.id, label: 'Alvo Atualizado' }, unit: { id: 'unit-norte', name: 'Unidade Norte', acronym: 'UN' }, result: 'success', before: { name: 'Alvo Antigo', registration: '50001', role: 'unit_user', situation: 'active', unit: local.unit }, after: { name: 'Alvo Atualizado', registration: '50002', role: 'unit_user', situation: 'active', unit: { id: 'unit-norte', name: 'Unidade Norte', acronym: 'UN' } } }); expect(JSON.stringify(response.body)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i); });
  it('updates a user to DITEL admin only when the unit is null', async () => { const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Promover', registration: '50003', role: 'unit_user', situation: 'blocked', unit: local.unit, passwordHash }); const response = await updateUser(admin, user.id, updateBody(user, { name: 'Promover Admin', registration: '50003', role: 'ditel_admin', unit: null })); expect(response.status).toBe(200); expect(response.body).toMatchObject({ name: 'Promover Admin', registration: '50003', role: 'ditel_admin', situation: 'blocked', unit: null }); });
  it('rejects unsafe user edit payloads and keeps situation in the dedicated flow', async () => { await UnitModel.create({ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }); const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Payload Seguro', registration: '50004', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const cases = [{ name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit, situation: 'blocked' }, { name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit, password: 'segredo' }, { name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit, passwordHash: 'hash' }, { name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit, token: 'abc' }, { name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit, sessionId: 'abc' }, { name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit, extra: true }]; for (const body of cases) { const response = await updateUser(admin, user.id, updateBody(user, body)); expect(response.status).toBe(400); expect(response.body.code).toBe('INVALID_USER'); } const missingToken = await updateUser(admin, user.id, { name: 'Novo', registration: '50004', role: 'unit_user', unit: local.unit }); expect(missingToken.status).toBe(400); expect(missingToken.body.code).toBe('INVALID_USER'); const stored = await UserModel.findById(user.id).select('name registration role situation unit').lean().orFail(); expect(stored).toMatchObject({ name: 'Payload Seguro', registration: '50004', role: 'unit_user', situation: 'active', unit: local.unit }); });
  it('rejects duplicate registrations, inactive or mismatched units, and invalid DITEL scope', async () => { await UnitModel.create([{ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }, { id: 'unit-inactive', name: 'Inativa', acronym: 'INA', active: false }]); const passwordHash = await hashPassword('password'); const target = await UserModel.create({ name: 'Alvo', registration: '50005', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); await UserModel.create({ name: 'Duplicado', registration: '50006', role: 'ditel_admin', situation: 'active', unit: null, passwordHash }); const duplicate = await updateUser(admin, target.id, updateBody(target, { name: 'Alvo', registration: '50006', role: 'unit_user', unit: local.unit })); const missingUnit = await updateUser(admin, target.id, updateBody(target, { name: 'Alvo', registration: '50005', role: 'unit_user', unit: null })); const inactiveUnit = await updateUser(admin, target.id, updateBody(target, { name: 'Alvo', registration: '50005', role: 'unit_user', unit: { id: 'unit-inactive', name: 'Inativa', acronym: 'INA' } })); const mismatchedUnit = await updateUser(admin, target.id, updateBody(target, { name: 'Alvo', registration: '50005', role: 'unit_user', unit: { id: local.unit.id, name: 'Nome Errado', acronym: local.unit.acronym } })); const invalidDitel = await updateUser(admin, target.id, updateBody(target, { name: 'Alvo', registration: '50005', role: 'ditel_admin', unit: local.unit })); expect([duplicate.status, duplicate.body.code]).toEqual([409, 'REGISTRATION_CONFLICT']); expect([missingUnit, inactiveUnit, mismatchedUnit, invalidDitel].map((response) => [response.status, response.body.code])).toEqual([[400, 'INVALID_USER'], [400, 'INVALID_USER'], [400, 'INVALID_USER'], [400, 'INVALID_USER']]); expect((await UserModel.findById(target.id).lean())?.registration).toBe('50005'); });
  it('rejects stale administrative user edit tokens with a conflict and does not audit success', async () => { await UnitModel.create({ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }); const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Concorrente', registration: '50011', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const staleUpdatedAt = user.updatedAt.toISOString(); await UserModel.updateOne({ _id: user.id }, { $set: { name: 'Alteração Paralela' } }); const response = await updateUser(admin, user.id, { name: 'Sobrescrever', registration: '50012', role: 'unit_user', unit: local.unit, updatedAt: staleUpdatedAt }); expect(response.status).toBe(409); expect(response.body).toEqual({ code: 'USER_CONFLICT', message: 'Usuário alterado por outra operação. Recarregue os dados e tente novamente.' }); const stored = await UserModel.findById(user.id).select('name registration role situation unit').lean().orFail(); expect(stored).toMatchObject({ name: 'Alteração Paralela', registration: '50011', role: 'unit_user', situation: 'active', unit: local.unit }); const events = await AuditEventModel.find({ action: 'admin.users.update' }).lean(); expect(events).toHaveLength(1); expect(events[0]).toMatchObject({ action: 'admin.users.update', userId: 'a', result: 'failure', reason: null }); expect(JSON.stringify(events)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i); });
  it('allows only DITEL admins to edit users and audits failures without secrets', async () => { await UnitModel.create({ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }); const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Restrito', registration: '50007', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); const response = await updateUser(local, user.id, updateBody(user, { name: 'Indevido', registration: '50008', role: 'unit_user', unit: local.unit })); expect(response.status).toBe(403); expect((await UserModel.findById(user.id).lean())?.name).toBe('Restrito'); const event = await AuditEventModel.findOne({ action: 'admin.users.update' }).lean(); expect(event).toMatchObject({ action: 'admin.users.update', userId: 'u', result: 'failure', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i); });
  it('rolls back a user edit and returns 503 when the success audit fails', async () => { await UnitModel.create({ id: local.unit.id, name: local.unit.name, acronym: local.unit.acronym, active: true }); const passwordHash = await hashPassword('password'); const user = await UserModel.create({ name: 'Rollback Edit', registration: '50009', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash }); vi.spyOn(AuditEventModel, 'create').mockRejectedValueOnce(new Error('simulated audit outage') as never); const response = await updateUser(admin, user.id, updateBody(user, { name: 'Não Persistir', registration: '50010', role: 'unit_user', unit: local.unit })); expect(response.status).toBe(503); expect(response.body).toEqual({ code: 'AUDIT_UNAVAILABLE', message: 'Não foi possível registrar auditoria.' }); const stored = await UserModel.findById(user.id).select('name registration role unit situation').lean().orFail(); expect(stored).toMatchObject({ name: 'Rollback Edit', registration: '50009', role: 'unit_user', unit: local.unit, situation: 'active' }); });
  it('creates a DITEL admin without a unit and defaults it to active', async () => { const response = await createUser(admin, { name: 'Admin Secundário', registration: '30002', role: 'ditel_admin', password: 'senha-admin-segura' }); expect(response.status).toBe(201); expect(response.body).toMatchObject({ name: 'Admin Secundário', registration: '30002', role: 'ditel_admin', situation: 'active', unit: null }); });
  it('rejects missing, unknown, and inactive unit references for unit users', async () => { await UnitModel.create({ id: 'unit-inactive', name: 'Inativa', acronym: 'INA', active: false }); const missing = await createUser(admin, { name: 'Sem Unidade', registration: '30003', role: 'unit_user', password: 'senha-segura' }); const unknown = await createUser(admin, { name: 'Unidade Desconhecida', registration: '30004', role: 'unit_user', password: 'senha-segura', unit: { id: 'unknown', name: 'Desconhecida', acronym: 'UNK' } }); const inactive = await createUser(admin, { name: 'Unidade Inativa', registration: '30005', role: 'unit_user', password: 'senha-segura', unit: { id: 'unit-inactive', name: 'Inativa', acronym: 'INA' } }); expect([missing, unknown, inactive].map((response) => [response.status, response.body.code])).toEqual([[400, 'INVALID_USER'], [400, 'INVALID_USER'], [400, 'INVALID_USER']]); expect(await UserModel.countDocuments()).toBe(0); });
  it('rejects duplicate registrations with a conflict and audits the failure without secrets', async () => { const body = { name: 'Duplicada', registration: '30006', role: 'ditel_admin', password: 'senha-duplicada' }; expect((await createUser(admin, body)).status).toBe(201); const response = await createUser(admin, body); expect(response.status).toBe(409); expect(response.body.code).toBe('REGISTRATION_CONFLICT'); const event = await AuditEventModel.findOne({ action: 'admin.users.create', result: 'failure' }).lean(); expect(event).toMatchObject({ action: 'admin.users.create', userId: 'a', result: 'failure', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId|senha-duplicada/i); });
  it('allows only DITEL admins to create users and audits the failure', async () => { const response = await createUser(local, { name: 'Não Autorizado', registration: '30007', role: 'ditel_admin', password: 'senha-nao-autorizada' }); expect(response.status).toBe(403); expect(await UserModel.countDocuments()).toBe(0); const event = await AuditEventModel.findOne({ action: 'admin.users.create' }).lean(); expect(event).toMatchObject({ action: 'admin.users.create', userId: 'u', result: 'failure', reason: null }); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId|senha-nao-autorizada/i); });
  it('resets an active user password with a server-generated temporary password, revokes sessions, and audits without secrets', async () => { const passwordHash = await hashPassword('senha-antiga'); const user = await UserModel.create({ name: 'Resetável', registration: '40001', role: 'ditel_admin', situation: 'active', unit: null, passwordHash }); const other = await UserModel.create({ name: 'Outro', registration: '40002', role: 'ditel_admin', situation: 'active', unit: null, passwordHash }); const now = new Date(); const future = new Date(now.getTime() + 60_000); await SessionModel.create([{ tokenDigest: 'target-session-a', userId: user.id, lastActivityAt: now, expiresAt: future }, { tokenDigest: 'target-session-b', userId: user.id, lastActivityAt: now, expiresAt: future }, { tokenDigest: 'other-session', userId: other.id, lastActivityAt: now, expiresAt: future }]); const response = await resetPassword(admin, user.id, { password: 'senha-injetada-pelo-cliente' }); expect(response.status).toBe(200); expect(Object.keys(response.body).sort()).toEqual(['mustChangePassword', 'temporaryPassword', 'userId']); expect(response.body).toMatchObject({ userId: user.id, mustChangePassword: true }); expect(response.body.temporaryPassword).toEqual(expect.any(String)); expect(response.body.temporaryPassword).not.toBe('senha-injetada-pelo-cliente'); expect(response.body.temporaryPassword.length).toBeGreaterThanOrEqual(20); const stored = await UserModel.findById(user.id).select('+passwordHash mustChangePassword').lean().orFail(); const storedPasswordHash = stored.passwordHash as string; expect(storedPasswordHash).not.toBe('senha-antiga'); await expect(verifyPassword('senha-antiga', storedPasswordHash)).resolves.toBe(false); await expect(verifyPassword('senha-injetada-pelo-cliente', storedPasswordHash)).resolves.toBe(false); await expect(verifyPassword(response.body.temporaryPassword, storedPasswordHash)).resolves.toBe(true); expect(stored.mustChangePassword).toBe(true); const sessions = await SessionModel.find().sort({ tokenDigest: 1 }).lean(); expect(sessions.filter((session) => session.userId === user.id).every((session) => session.revokedAt instanceof Date)).toBe(true); expect(sessions.find((session) => session.userId === other.id)?.revokedAt ?? null).toBeNull(); const event = await AuditEventModel.findOne({ action: 'admin.users.credential_reset' }).lean(); expect(event).toMatchObject({ action: 'admin.users.credential_reset', module: 'administration', userId: 'a', actor: { id: 'a', name: 'Admin', registration: 'a', role: 'ditel_admin' }, entity: { type: 'user', id: user.id, label: 'Resetável' }, result: 'success', reason: null, before: { requiresCredentialChange: false }, after: { requiresCredentialChange: true, sessionsRevoked: 2 } }); expect(JSON.stringify(event)).not.toContain(response.body.temporaryPassword); expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId|senha-injetada-pelo-cliente/i); });
  it('rejects password reset without DITEL permission or with invalid, missing, and inactive targets', async () => { const passwordHash = await hashPassword('senha-antiga'); const inactive = await UserModel.create({ name: 'Inativo Reset', registration: '40003', role: 'ditel_admin', situation: 'inactive', unit: null, passwordHash }); expect((await request(createApp()).post(`/api/v1/admin/users/${inactive.id}/password-reset`)).status).toBe(401); expect((await resetPassword(local, inactive.id)).status).toBe(403); expect((await resetPassword(admin, 'not-an-object-id')).status).toBe(400); expect((await resetPassword(admin, new mongoose.Types.ObjectId().toString())).status).toBe(404); const inactiveResponse = await resetPassword(admin, inactive.id); expect(inactiveResponse.status).toBe(409); expect(inactiveResponse.body.code).toBe('INVALID_PASSWORD_RESET_TARGET'); const stored = await UserModel.findById(inactive.id).select('situation mustChangePassword').lean().orFail(); expect(stored).toMatchObject({ situation: 'inactive' }); expect(stored.mustChangePassword ?? false).toBe(false); const events = await AuditEventModel.find({ action: 'admin.users.credential_reset' }).lean(); expect(events.map((event) => event.result)).toEqual(['failure', 'failure', 'failure', 'failure']); expect(JSON.stringify(events)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); });
  it('handles concurrent password resets without reusing a temporary password', async () => { const passwordHash = await hashPassword('senha-antiga'); const user = await UserModel.create({ name: 'Reset Concorrente', registration: '40004', role: 'ditel_admin', situation: 'active', unit: null, passwordHash }); const responses = await Promise.all([resetPassword(admin, user.id), resetPassword(admin, user.id)]); expect(responses.map((response) => response.status)).toEqual([200, 200]); const temporaryPasswords = responses.map((response) => response.body.temporaryPassword as string); expect(new Set(temporaryPasswords).size).toBe(2); expect(temporaryPasswords.every((temporaryPassword) => typeof temporaryPassword === 'string' && temporaryPassword.length >= 20)).toBe(true); const stored = await UserModel.findById(user.id).select('+passwordHash mustChangePassword').lean().orFail(); await expect(Promise.all(temporaryPasswords.map((temporaryPassword) => verifyPassword(temporaryPassword, stored.passwordHash as string)))).resolves.toContain(true); expect(stored.mustChangePassword).toBe(true); const events = await AuditEventModel.find({ action: 'admin.users.credential_reset', result: 'success' }).lean(); expect(events).toHaveLength(2); expect(JSON.stringify(events)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i); for (const temporaryPassword of temporaryPasswords) expect(JSON.stringify(events)).not.toContain(temporaryPassword); });
  it('returns the must-change-password state on the next login after a reset', async () => { const passwordHash = await hashPassword('senha-antiga'); const user = await UserModel.create({ name: 'Login Resetado', registration: '40005', role: 'ditel_admin', situation: 'active', unit: null, passwordHash }); const reset = await resetPassword(admin, user.id); expect(reset.status).toBe(200); const login = await request(createApp()).post('/api/v1/auth/login').send({ registration: '40005', password: reset.body.temporaryPassword }); expect(login.status).toBe(200); expect(login.body).toMatchObject({ userId: user.id, registration: '40005', role: 'ditel_admin', unit: null, mustChangePassword: true }); });

  it('deactivates an active user, revokes sessions, audits and returns { id, situation } without secrets', async () => {
    const passwordHash = await hashPassword('senha');
    const user = await UserModel.create({ name: 'Excluível', registration: '60001', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash });
    const future = new Date(Date.now() + 60_000);
    await SessionModel.create({ tokenDigest: 'session-to-revoke', userId: user.id, lastActivityAt: new Date(), expiresAt: future });

    const response = await deactivateUser(admin, user.id);

    expect(response.status).toBe(200);
    expect(response.body).toEqual({ id: user.id, situation: 'inactive' });
    const stored = await UserModel.findById(user.id).select('situation').lean();
    expect(stored?.situation).toBe('inactive');
    const sessions = await SessionModel.find({ userId: user.id }).lean();
    expect(sessions.every((session) => session.revokedAt instanceof Date)).toBe(true);
    const event = await AuditEventModel.findOne({ action: 'admin.users.delete' }).lean();
    expect(event).toMatchObject({
      action: 'admin.users.delete',
      module: 'administration',
      userId: 'a',
      actor: { id: 'a', name: 'Admin', registration: 'a', role: 'ditel_admin' },
      entity: { type: 'user', id: user.id, label: 'Excluível' },
      unit: local.unit,
      result: 'success',
      before: { situation: 'active' },
      after: { situation: 'inactive' },
    });
    expect(JSON.stringify(response.body)).not.toMatch(/passwordHash|password|token|tokenDigest|sessionId/i);
    expect(JSON.stringify(event)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i);
  });

  it('rejects deactivation of the authenticated user itself with 409 and audits failure', async () => {
    const passwordHash = await hashPassword('senha');
    const self = await UserModel.create({ name: 'Admin Próprio', registration: '60002', role: 'ditel_admin', situation: 'active', unit: null, passwordHash });
    const selfContext: SessionContext = { userId: self.id, name: 'Admin Próprio', registration: '60002', role: 'ditel_admin', unit: null };

    const response = await deactivateUser(selfContext, self.id);

    expect(response.status).toBe(409);
    expect(response.body.code).toBe('SELF_DEACTIVATION_FORBIDDEN');
    expect((await UserModel.findById(self.id).select('situation').lean())?.situation).toBe('active');
    const event = await AuditEventModel.findOne({ action: 'admin.users.delete', result: 'failure' }).lean();
    expect(event).toMatchObject({ action: 'admin.users.delete', userId: self.id, result: 'failure' });
  });

  it('rejects deactivation of an already inactive user with 409 and audits failure', async () => {
    const passwordHash = await hashPassword('senha');
    const user = await UserModel.create({ name: 'Já Inativo', registration: '60003', role: 'unit_user', situation: 'inactive', unit: local.unit, passwordHash });

    const response = await deactivateUser(admin, user.id);

    expect(response.status).toBe(409);
    expect(response.body.code).toBe('INVALID_SITUATION_TRANSITION');
    const event = await AuditEventModel.findOne({ action: 'admin.users.delete', result: 'failure' }).lean();
    expect(event).toMatchObject({ action: 'admin.users.delete', userId: 'a', result: 'failure' });
  });

  it('denies deactivation to unit users with 403 and audits failure', async () => {
    const passwordHash = await hashPassword('senha');
    const user = await UserModel.create({ name: 'Restrito', registration: '60004', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash });

    const response = await deactivateUser(local, user.id);

    expect(response.status).toBe(403);
    expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('active');
    const event = await AuditEventModel.findOne({ action: 'admin.users.delete', result: 'failure' }).lean();
    expect(event).toMatchObject({ action: 'admin.users.delete', userId: 'u', result: 'failure' });
  });

  it('rejects deactivation of missing or invalid users with 404/400 and audits failure', async () => {
    expect((await deactivateUser(admin, 'not-an-object-id')).status).toBe(400);
    expect((await deactivateUser(admin, new mongoose.Types.ObjectId().toString())).status).toBe(404);
    const events = await AuditEventModel.find({ action: 'admin.users.delete' }).lean();
    expect(events).toHaveLength(2);
    expect(events.every((event) => event.result === 'failure')).toBe(true);
    expect(JSON.stringify(events)).not.toMatch(/passwordHash|password|senha|token|tokenDigest|sessionId/i);
  });

  it('rolls back deactivation and returns 503 when the success audit fails', async () => {
    const passwordHash = await hashPassword('senha');
    const user = await UserModel.create({ name: 'Rollback Delete', registration: '60005', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash });
    vi.spyOn(AuditEventModel, 'create').mockRejectedValueOnce(new Error('simulated audit outage') as never);

    const response = await deactivateUser(admin, user.id);

    expect(response.status).toBe(503);
    expect(response.body).toEqual({ code: 'AUDIT_UNAVAILABLE', message: 'Não foi possível registrar auditoria.' });
    expect((await UserModel.findById(user.id).select('situation').lean())?.situation).toBe('active');
  });

  it('deactivated users cannot log in', async () => {
    const passwordHash = await hashPassword('senha-excluida');
    const user = await UserModel.create({ name: 'Sem Acesso', registration: '60006', role: 'unit_user', situation: 'active', unit: local.unit, passwordHash, mustChangePassword: false });
    await deactivateUser(admin, user.id);

    const login = await request(createApp()).post('/api/v1/auth/login').send({ registration: '60006', password: 'senha-excluida' });
    expect(login.status).toBe(401);
    expect(login.body.code).toBe('INVALID_CREDENTIALS');
  });
});
